import com.android.build.api.dsl.ApplicationExtension
import com.android.build.gradle.internal.api.BaseVariantOutputImpl
import org.gradle.kotlin.dsl.*
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.BufferedOutputStream
import java.math.BigInteger
import java.net.HttpURLConnection
import java.net.URL
import java.security.DigestInputStream
import java.security.MessageDigest

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

fun sha256Of(f: File): String {
    val digest = MessageDigest.getInstance("SHA-256")
    f.inputStream().use { inputStream ->
        val buffer = ByteArray(8192)
        var read: Int
        while (inputStream.read(buffer).also { read = it } > 0) {
            digest.update(buffer, 0, read)
        }
    }
    var checksum = BigInteger(1, digest.digest()).toString(16)
    while (checksum.length < 64) {
        checksum = "0$checksum"
    }
    return checksum
}

val bootstrapZipFile = file("$projectDir/src/main/cpp/bootstrap-aarch64.zip")
val bootstrapStampFile = file("$projectDir/src/main/cpp/generated/bootstrap-stamp.S")
val bootstrapZipSha256 = if (bootstrapZipFile.exists()) sha256Of(bootstrapZipFile) else "missing"
val bootstrapZipSize = if (bootstrapZipFile.exists()) bootstrapZipFile.length() else -1L

tasks.register("generateBootstrapStamp") {
    inputs.file(bootstrapZipFile)
    outputs.file(bootstrapStampFile)
    doLast {
        val sha = if (bootstrapZipFile.exists()) sha256Of(bootstrapZipFile) else "missing"
        val size = if (bootstrapZipFile.exists()) bootstrapZipFile.length() else -1L
        bootstrapStampFile.parentFile.mkdirs()
        bootstrapStampFile.writeText(
        """
        // Generated by Gradle. Do not edit.
        .section .rodata
        .globl BOOTSTRAP_SHA256
        .type BOOTSTRAP_SHA256, @object
        BOOTSTRAP_SHA256:
           .asciz "${sha}"
    
        .globl BOOTSTRAP_SIZE
        .type BOOTSTRAP_SIZE, @object
        BOOTSTRAP_SIZE:
            .quad ${size}
        """.trimIndent()
    )
    }
}

android {
    namespace = "com.neonide.studio"
    compileSdk = 36
    ndkVersion = "29.0.14033849"

    defaultConfig {
        applicationId = "com.neonide.studio"
        minSdk = 21
        targetSdk = 28
        versionCode = 1
        versionName = "0.1"

        manifestPlaceholders.putAll(
        mapOf(
            "TERMUX_PACKAGE_NAME" to "com.neonide.studio",
            "TERMUX_APP_NAME" to "NeonIDE Studio",
            "TERMUX_API_APP_NAME" to "NeonIDE Studio:API",
            "TERMUX_BOOT_APP_NAME" to "NeonIDE Studio:Boot",
            "TERMUX_FLOAT_APP_NAME" to "NeonIDE Studio:Float",
            "TERMUX_STYLING_APP_NAME" to "NeonIDE Studio:Styling",
            "TERMUX_TASKER_APP_NAME" to "NeonIDE Studio:Tasker",
            "TERMUX_WIDGET_APP_NAME" to "NeonIDE Studio:Widget"
            )as Map<String, Any>
        )
        
        ndk {
            abiFilters += "arm64-v8a"
        }
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    signingConfigs {
        getByName("debug") {
            storeFile = file("testkey_untrusted.jks")
            keyAlias = "alias"
            storePassword = "xrj45yWGLbsO7W0v"
            keyPassword = "xrj45yWGLbsO7W0v"
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    externalNativeBuild {
        ndkBuild {
            path("src/main/cpp/Android.mk")
        }
    }

    lint {
        disable += "ProtectedPermissions"
    }

    testOptions {
        unitTests.isIncludeAndroidResources = true
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {
    implementation("androidx.annotation:annotation:1.3.0")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.core:core:1.12.0")
    implementation("androidx.documentfile:documentfile:1.0.1")
    implementation("androidx.drawerlayout:drawerlayout:1.1.1")
    implementation("androidx.preference:preference:1.1.1")
    implementation("androidx.viewpager:viewpager:1.0.0")
    implementation("androidx.viewpager2:viewpager2:1.1.0")
    implementation("androidx.fragment:fragment-ktx:1.6.2")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
    implementation("androidx.recyclerview:recyclerview:1.3.2")
    implementation("androidx.window:window:1.0.0-alpha09")
    implementation("com.google.android.material:material:1.13.0")
    implementation("com.google.guava:guava:33.5.0-jre") {
        exclude(group = "org.codehaus.mojo", module = "animal-sniffer-annotations")
        
    }
    implementation("commons-io:commons-io:2.5")
    implementation("io.noties.markwon:core:${project.properties["markwonVersion"]}")
    implementation("io.noties.markwon:ext-strikethrough:${project.properties["markwonVersion"]}")
    implementation("io.noties.markwon:linkify:${project.properties["markwonVersion"]}")
    implementation("io.noties.markwon:recycler:${project.properties["markwonVersion"]}")
    implementation("org.lsposed.hiddenapibypass:hiddenapibypass:6.1")
    implementation("com.termux:termux-am-library:v2.0.0")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.2.21")
    implementation("org.codelibs:jhighlight:1.1.1")

    // Sora Editor dependencies
    implementation("androidx.collection:collection:1.5.0")
    implementation("com.google.code.gson:gson:2.13.2")
    implementation("org.jruby.jcodings:jcodings:1.0.63")
    implementation("org.jruby.joni:joni:2.2.6")
    implementation("org.snakeyaml:snakeyaml-engine:2.10")
    implementation("com.squareup.moshi:moshi:1.15.2")
    implementation("org.eclipse.jdt:org.eclipse.jdt.annotation:2.4.100")
    implementation("io.github.dingyi222666.monarch:monarch:1.0.3")
    implementation("io.github.dingyi222666.monarch:monarch-json-loader:1.0.2")
    implementation("io.github.dingyi222666.regex-lib:regex-lib-oniguruma:1.0.3")
    implementation("io.github.dingyi222666.regex-lib:regex-lib-re2j:1.0.2")
    implementation("com.itsaky.androidide.treesitter:android-tree-sitter:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-java:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-kotlin:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-xml:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-aidl:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-python:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-c:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-cpp:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-json:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-log:4.3.2")
    implementation("com.itsaky.androidide.treesitter:tree-sitter-properties:4.3.2")
    implementation("com.itsaky.androidide.treesitter:annotations:4.3.2")

    annotationProcessor(files("libs/annotation-processors.jar", "libs/annotations.jar"))
    annotationProcessor("com.squareup:javapoet:1.13.0")

    implementation("io.github.dingyi222666.monarch:monarch-language-pack:1.0.2")
    implementation("org.eclipse.lsp4j:org.eclipse.lsp4j:0.24.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
    implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"), "exclude" to listOf("annotation-processors.jar", "annotations.jar"))))

    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.robolectric:robolectric:4.10")
    testImplementation("androidx.arch.core:core-testing:2.2.0")
    androidTestImplementation("androidx.test.ext:junit:1.1.3")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.4.0")
}

tasks.register("cleanNativeIfBootstrapChanged") {
    val stateFile = file("${layout.buildDirectory.asFile.get()}/bootstrap-embedded.sha256")
    inputs.file(bootstrapZipFile)
    outputs.file(stateFile)

    doLast {
        val currentSha = if (bootstrapZipFile.exists()) sha256Of(bootstrapZipFile) else "missing"
        val previousSha = if (stateFile.exists()) stateFile.readText().trim() else null

        if (previousSha == null || previousSha != currentSha) {
            logger.lifecycle("Bootstrap zip changed (old=${previousSha}, new=${currentSha}). Cleaning native intermediates...")
            delete(
                file("${layout.buildDirectory.asFile.get()}/intermediates/ndkBuild"),
                file("${layout.buildDirectory.asFile.get()}/intermediates/cxx"),
                file("${layout.buildDirectory.asFile.get()}/intermediates/merged_native_libs"),
                file("${layout.buildDirectory.asFile.get()}/intermediates/stripped_native_libs")
            )
        }

        stateFile.parentFile.mkdirs()
        stateFile.writeText("$currentSha\n")
    }
}


afterEvaluate {
    val zip = file("$projectDir/src/main/cpp/bootstrap-aarch64.zip")
    val stamp = file("$projectDir/src/main/cpp/generated/bootstrap-stamp.S")

    tasks.matching { 
        it.name.startsWith("externalNativeBuild") || 
        it.name.startsWith("configureNdkBuild") || 
        it.name.startsWith("buildNdkBuild") 
    }.configureEach {
        dependsOn(tasks.named("generateBootstrapStamp"))
        inputs.file(zip)
        inputs.file(stamp)
    }

    tasks.matching { it.name == "packageDebug" || it.name == "packageRelease" }.configureEach {
        doFirst {
            outputs.files.files.forEach { f ->
                if (f.exists() && f.isFile) {
                    logger.lifecycle("Deleting stale APK output before packaging: ${f}")
                    f.delete()
                }
            }
        }
    }
}

tasks.named("preBuild") {
    dependsOn(
        tasks.named("generateBootstrapStamp"),
        tasks.named("cleanNativeIfBootstrapChanged")
    )
}